# Generated by Django 5.2.8 on 2025-11-30 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='signUpVals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signUpName', models.CharField()),
                ('signUpEmail', models.EmailField(max_length=254)),
                ('signUpPass', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('tds', models.FloatField()),
                ('hardness', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('conductivity', models.FloatField(blank=True, null=True)),
                ('wqi', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
